project_id = "yrvriyyoawqpsruqarms"

[functions.send-sms]
verify_jwt = true

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.send-daily-milk-summary]
verify_jwt = false