// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yrvriyyoawqpsruqarms.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlydnJpeXlvYXdxcHNydXFhcm1zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkxNjczOTYsImV4cCI6MjA3NDc0MzM5Nn0.sfhHQvdLspDyalmJbAqwomE8cKFLcR5LvrQwjOxVM2A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});